version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /etc/localtime:/etc/localtime
      - /usr/local/python3:/usr/local/python3
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai"
      PATH: "/opt/java/openjdk/bin:/usr/local/python3/bin:/bin:/usr/bin:/usr/local/bin"
      PYTHONPATH: "/usr/local/python3/lib/python3.10/site-packages"

volumes:
  jenkins-data:
