version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /etc/localtime:/etc/localtime
      - /usr/local/python3:/usr/local/python3
      # 把宿主机的 /usr/local/python3 目录挂载到 jenkins 容器的 /usr/local/python3 目录下，这样 jenkins 容器就可以使用宿主机的 python3 环境
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai"
volumes:
  jenkins-data: