version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    depends_on:
      - python
    ports:
      - 9666:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /etc/localtime:/etc/localtime
      - /usr/local/python3:/usr/local/python3
       # 把宿主机的 /usr/local/python3 目录挂载到 jenkins 容器的 /usr/local/python3 目录下，这样 jenkins 容器就可以使用宿主机的 python3 环境
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai"
    networks:
      - mynet

  python:
    #这个镜像自带了 python3.10 的环境。这两个容器是独立的，有各自的 python 版本，不会相互影响。
    #如果你只是需要在jenkins运行python脚本，你可以把下面的部分删除了，
    #因为你已经把宿主机的 /usr/local/python3 目录挂载到 jenkins 容器的 /usr/local/python3 目录下，所以你可以在 jenkins 容器中使用 python3 命令来运行python脚本。
    #你不需要另外创建一个 python 容器来运行 /root/lpq/code 目录下的 run_cmd.py 脚本，除非你有特殊的需求或者依赖。
    image: python:3.10-slim-buster
    container_name: python
    restart: always
    volumes:
      - /root/lpq/code:/code
    command: python /code/run_cmd.py
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
volumes:
  jenkins-data: